"""
Exam API endpoints.

Handles exam generation, retrieval, submission, and evaluation.
"""

from datetime import datetime
from typing import List
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.api.deps import get_current_user, get_db
from app.models.user import User
from app.models.exam import Exam, ExamQuestion, ExamAttempt, ExamAnswer
from app.schemas.exam import (
    ExamGenerate,
    ExamResponse,
    ExamListResponse,
    ExamQuestionResponse,
    LatestAttemptSummary,
    SubmitExam,
    ExamResultResponse,
    ExamAnswerFeedback,
)

router = APIRouter()


@router.post("/generate", response_model=ExamResponse, status_code=status.HTTP_201_CREATED)
def generate_exam(
    data: ExamGenerate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generate an exam from study materials using AI.

    The LLM creates questions based on document chunks stored
    for the specified subject. Supports multiple choice and
    short answer question types.

    Args:
        data: Exam generation configuration

    Returns:
        ExamResponse: Generated exam with questions (answers hidden)
    """
    # Validate at least one scope is provided
    if not any([data.subject_id, data.course_id, data.workspace_id, data.document_ids]):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="At least one of subject_id, course_id, workspace_id, or document_ids must be provided",
        )

    from app.services.llm_client import LLMClient
    from app.services.exam_generator import ExamGeneratorService

    user_provider = getattr(current_user, "llm_provider", None) or "auto"
    llm = LLMClient(provider=None if user_provider == "auto" else user_provider)
    generator = ExamGeneratorService(db=db, llm=llm)

    try:
        exam = generator.generate_exam(
            subject_id=data.subject_id,
            user_id=current_user.id,
            mc_count=data.mc_count,
            short_answer_count=data.short_answer_count,
            difficulty=data.difficulty,
            title=data.title,
            document_ids=data.document_ids,
            course_id=data.course_id,
            workspace_id=data.workspace_id,
            num_options=data.num_options,
        )
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )

    return exam


@router.get("/", response_model=List[ExamListResponse])
def list_exams(
    subject_id: UUID = None,
    course_id: UUID = None,
    workspace_id: UUID = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    List exams with attempt summaries, optionally filtered by subject, course, or workspace.

    Only returns exams generated by the current user (via document ownership).
    Includes attempt_count and latest_attempt summary for each exam.

    Args:
        subject_id: Optional filter by subject
        course_id: Optional filter by course (via subject → course)
        workspace_id: Optional filter by workspace (via subject → course → workspace)

    Returns:
        List of exams with questions and attempt summaries
    """
    from app.models.subject import Subject
    from app.models.course import Course
    from app.models.workspace import Workspace

    query = db.query(Exam)

    if subject_id:
        query = query.filter(Exam.subject_id == subject_id)
    elif course_id:
        subject_ids = [s.id for s in db.query(Subject).filter(Subject.course_id == course_id).all()]
        query = query.filter(Exam.subject_id.in_(subject_ids))
    elif workspace_id:
        course_ids = [c.id for c in db.query(Course).filter(Course.workspace_id == workspace_id).all()]
        subject_ids = [s.id for s in db.query(Subject).filter(Subject.course_id.in_(course_ids)).all()]
        query = query.filter(Exam.subject_id.in_(subject_ids))

    # Filter by user ownership
    user_workspace_ids = [w.id for w in db.query(Workspace).filter(Workspace.user_id == current_user.id).all()]
    user_course_ids = [c.id for c in db.query(Course).filter(Course.workspace_id.in_(user_workspace_ids)).all()]
    user_subject_ids = [s.id for s in db.query(Subject).filter(Subject.course_id.in_(user_course_ids)).all()]
    query = query.filter(Exam.subject_id.in_(user_subject_ids))

    exams = query.order_by(Exam.created_at.desc()).limit(50).all()

    # Enrich with attempt data
    result = []
    for exam in exams:
        # Count completed attempts for this user
        attempts = (
            db.query(ExamAttempt)
            .filter(
                ExamAttempt.exam_id == exam.id,
                ExamAttempt.user_id == current_user.id,
                ExamAttempt.status == "completed",
            )
            .order_by(ExamAttempt.completed_at.desc())
            .all()
        )

        latest = None
        if attempts:
            a = attempts[0]
            latest = LatestAttemptSummary(
                score=a.score or 0,
                correct_answers=a.correct_answers or 0,
                total_questions=a.total_questions or 0,
                completed_at=a.completed_at,
            )

        result.append(
            ExamListResponse(
                id=exam.id,
                subject_id=exam.subject_id,
                title=exam.title,
                description=exam.description,
                question_count=exam.question_count,
                mc_count=exam.mc_count,
                short_answer_count=exam.short_answer_count,
                questions=exam.questions,
                created_at=exam.created_at,
                attempt_count=len(attempts),
                latest_attempt=latest,
            )
        )

    return result


@router.get("/{exam_id}", response_model=ExamResponse)
def get_exam(
    exam_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a specific exam by ID.

    Args:
        exam_id: Exam UUID

    Returns:
        ExamResponse with questions (answers hidden for taking)
    """
    exam = db.query(Exam).filter(Exam.id == exam_id).first()
    if not exam:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Exam not found",
        )
    return exam


@router.post("/{exam_id}/start")
def start_exam_attempt(
    exam_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Start a new exam attempt.

    Creates an ExamAttempt record to track the session.

    Args:
        exam_id: Exam to start

    Returns:
        Dict with attempt_id and exam details
    """
    exam = db.query(Exam).filter(Exam.id == exam_id).first()
    if not exam:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Exam not found",
        )

    attempt = ExamAttempt(
        exam_id=exam_id,
        user_id=current_user.id,
        total_questions=exam.question_count,
        status="in_progress",
    )
    db.add(attempt)
    db.commit()
    db.refresh(attempt)

    return {
        "attempt_id": str(attempt.id),
        "exam_id": str(exam_id),
        "exam_title": exam.title,
        "total_questions": exam.question_count,
        "started_at": attempt.started_at.isoformat(),
    }


@router.post("/{exam_id}/submit", response_model=ExamResultResponse)
def submit_exam(
    exam_id: UUID,
    data: SubmitExam,
    attempt_id: UUID = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Submit exam answers for evaluation.

    Automatically grades MC questions and uses LLM for short answers.

    Args:
        exam_id: Exam being submitted
        data: All answers
        attempt_id: Optional attempt ID (creates one if not provided)

    Returns:
        ExamResultResponse with scores and feedback for each question
    """
    from app.services.llm_client import LLMClient
    from app.services.exam_generator import ExamGeneratorService

    # Get exam with questions
    exam = db.query(Exam).filter(Exam.id == exam_id).first()
    if not exam:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Exam not found",
        )

    # Get or create attempt
    if attempt_id:
        attempt = db.query(ExamAttempt).filter(ExamAttempt.id == attempt_id).first()
    else:
        attempt = ExamAttempt(
            exam_id=exam_id,
            user_id=current_user.id,
            total_questions=exam.question_count,
            status="in_progress",
        )
        db.add(attempt)
        db.flush()

    # Build question lookup
    questions_map = {str(q.id): q for q in exam.questions}

    user_provider = getattr(current_user, "llm_provider", None) or "auto"
    llm = LLMClient(provider=None if user_provider == "auto" else user_provider)
    generator = ExamGeneratorService(db=db, llm=llm)

    correct_count = 0
    total_score = 0
    feedbacks = []

    for answer_data in data.answers:
        question = questions_map.get(str(answer_data.question_id))
        if not question:
            continue

        is_correct = False
        score = 0.0
        feedback_text = ""
        user_answer = answer_data.user_answer.strip() if answer_data.user_answer else ""

        # Handle unanswered questions gracefully
        if not user_answer:
            is_correct = False
            score = 0.0
            if question.question_type == "mc":
                feedback_text = f"Not answered. The correct answer is {question.correct_answer}."
            else:
                feedback_text = "Not answered."
        elif question.question_type == "mc":
            # Automatic grading for multiple choice
            is_correct = (
                user_answer.upper()
                == (question.correct_answer or "").strip().upper()
            )
            score = 10.0 if is_correct else 0.0
            if is_correct:
                feedback_text = "Correct!"
                correct_count += 1
            else:
                feedback_text = (
                    f"Incorrect. The correct answer is {question.correct_answer}."
                )
        else:
            # LLM evaluation for short answer
            eval_result = generator.evaluate_short_answer(
                question_text=question.question_text,
                model_answer=question.model_answer or "",
                keywords=question.keywords or [],
                user_answer=user_answer,
            )
            is_correct = eval_result["is_correct"]
            score = eval_result["score"]
            feedback_text = eval_result["feedback"]
            if is_correct:
                correct_count += 1

        total_score += score

        # Save answer record
        exam_answer = ExamAnswer(
            attempt_id=attempt.id,
            question_id=question.id,
            user_answer=answer_data.user_answer,
            is_correct=is_correct,
            score=score,
            llm_feedback=feedback_text,
        )
        db.add(exam_answer)

        feedbacks.append(
            ExamAnswerFeedback(
                question_id=question.id,
                question_text=question.question_text,
                question_type=question.question_type,
                user_answer=answer_data.user_answer,
                correct_answer=question.correct_answer or question.model_answer,
                is_correct=is_correct,
                score=score,
                feedback=feedback_text,
                explanation=question.explanation,
            )
        )

    # Calculate final score as percentage
    total_questions = len(data.answers) or 1
    final_score = (total_score / (total_questions * 10)) * 100

    # Update attempt
    attempt.completed_at = datetime.utcnow()
    attempt.status = "completed"
    attempt.score = round(final_score, 1)
    attempt.correct_answers = correct_count

    db.commit()
    db.refresh(attempt)

    return ExamResultResponse(
        attempt_id=attempt.id,
        exam_id=exam.id,
        exam_title=exam.title,
        score=attempt.score,
        total_questions=total_questions,
        correct_answers=correct_count,
        answers=feedbacks,
        completed_at=attempt.completed_at,
    )


@router.get("/{exam_id}/attempts")
def list_attempts(
    exam_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    List all attempts for a specific exam by the current user.

    Args:
        exam_id: Exam to get attempts for

    Returns:
        List of attempt summaries
    """
    attempts = (
        db.query(ExamAttempt)
        .filter(
            ExamAttempt.exam_id == exam_id,
            ExamAttempt.user_id == current_user.id,
        )
        .order_by(ExamAttempt.started_at.desc())
        .all()
    )

    return [
        {
            "attempt_id": str(a.id),
            "started_at": a.started_at.isoformat() if a.started_at else None,
            "completed_at": a.completed_at.isoformat() if a.completed_at else None,
            "status": a.status,
            "score": a.score,
            "correct_answers": a.correct_answers,
            "total_questions": a.total_questions,
        }
        for a in attempts
    ]


@router.get("/{exam_id}/review", response_model=ExamResultResponse)
def review_latest_attempt(
    exam_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get the latest completed attempt results for review.

    Returns the full result with all answers, feedback, and correct answers
    so the user can review what they got right/wrong.

    Args:
        exam_id: Exam to review

    Returns:
        ExamResultResponse with full answer details
    """
    exam = db.query(Exam).filter(Exam.id == exam_id).first()
    if not exam:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Exam not found")

    attempt = (
        db.query(ExamAttempt)
        .filter(
            ExamAttempt.exam_id == exam_id,
            ExamAttempt.user_id == current_user.id,
            ExamAttempt.status == "completed",
        )
        .order_by(ExamAttempt.completed_at.desc())
        .first()
    )

    if not attempt:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No completed attempts found for this exam",
        )

    # Build question lookup
    questions_map = {str(q.id): q for q in exam.questions}

    feedbacks = []
    for ans in sorted(attempt.answers, key=lambda a: (questions_map.get(str(a.question_id), None) and questions_map[str(a.question_id)].question_order) or 0):
        question = questions_map.get(str(ans.question_id))
        if not question:
            continue
        feedbacks.append(
            ExamAnswerFeedback(
                question_id=ans.question_id,
                question_text=question.question_text,
                question_type=question.question_type,
                user_answer=ans.user_answer or "",
                correct_answer=question.correct_answer or question.model_answer,
                is_correct=ans.is_correct or False,
                score=ans.score,
                feedback=ans.llm_feedback,
                explanation=question.explanation,
            )
        )

    return ExamResultResponse(
        attempt_id=attempt.id,
        exam_id=exam.id,
        exam_title=exam.title,
        score=attempt.score or 0,
        total_questions=attempt.total_questions or 0,
        correct_answers=attempt.correct_answers or 0,
        answers=feedbacks,
        completed_at=attempt.completed_at,
    )


@router.delete("/{exam_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_exam(
    exam_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete an exam and all associated questions/attempts.

    Args:
        exam_id: Exam to delete
    """
    exam = db.query(Exam).filter(Exam.id == exam_id).first()
    if not exam:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Exam not found",
        )

    db.delete(exam)
    db.commit()


@router.get("/{exam_id}/export/json")
def export_exam_json(
    exam_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Export an exam as JSON with questions, correct answers, and attempt history.

    Includes everything needed to import and restore the exam.

    Args:
        exam_id: Exam to export

    Returns:
        JSON with exam, questions, and attempts
    """
    exam = db.query(Exam).filter(Exam.id == exam_id).first()
    if not exam:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Exam not found")

    # Get attempts for this user
    attempts = (
        db.query(ExamAttempt)
        .filter(ExamAttempt.exam_id == exam_id, ExamAttempt.user_id == current_user.id)
        .order_by(ExamAttempt.started_at.desc())
        .all()
    )

    export_data = {
        "version": "1.0",
        "exported_at": datetime.utcnow().isoformat(),
        "exam": {
            "title": exam.title,
            "description": exam.description,
            "question_count": exam.question_count,
            "mc_count": exam.mc_count,
            "short_answer_count": exam.short_answer_count,
            "created_at": exam.created_at.isoformat() if exam.created_at else None,
            "questions": [
                {
                    "question_order": q.question_order,
                    "question_type": q.question_type,
                    "question_text": q.question_text,
                    "options": q.options,
                    "correct_answer": q.correct_answer,
                    "model_answer": q.model_answer,
                    "keywords": q.keywords,
                    "explanation": q.explanation,
                    "difficulty": q.difficulty,
                    "topic": q.topic,
                }
                for q in sorted(exam.questions, key=lambda x: x.question_order)
            ],
        },
        "attempts": [
            {
                "started_at": a.started_at.isoformat() if a.started_at else None,
                "completed_at": a.completed_at.isoformat() if a.completed_at else None,
                "status": a.status,
                "score": a.score,
                "correct_answers": a.correct_answers,
                "total_questions": a.total_questions,
                "answers": [
                    {
                        "question_order": ans.question.question_order if ans.question else None,
                        "user_answer": ans.user_answer,
                        "is_correct": ans.is_correct,
                        "score": ans.score,
                        "feedback": ans.llm_feedback,
                    }
                    for ans in (a.answers or [])
                ],
            }
            for a in attempts
        ],
    }

    return export_data


@router.get("/{exam_id}/export/txt")
def export_exam_txt(
    exam_id: UUID,
    include_answers: bool = False,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Export an exam as plain text (printable format).

    Args:
        exam_id: Exam to export
        include_answers: Whether to include correct answers

    Returns:
        Plain text exam content
    """
    from fastapi.responses import PlainTextResponse

    exam = db.query(Exam).filter(Exam.id == exam_id).first()
    if not exam:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Exam not found")

    lines = []
    lines.append(f"{'=' * 60}")
    lines.append(f"  {exam.title}")
    lines.append(f"{'=' * 60}")
    if exam.description:
        lines.append(f"\n{exam.description}\n")
    lines.append(f"Total questions: {exam.question_count}")
    lines.append(f"{'─' * 60}\n")

    for q in sorted(exam.questions, key=lambda x: x.question_order):
        lines.append(f"Question {q.question_order}. [{q.difficulty}] [{q.question_type.upper()}]")
        lines.append(f"{q.question_text}\n")

        if q.question_type == "mc" and q.options:
            for i, opt in enumerate(q.options):
                letter = chr(65 + i)
                lines.append(f"  {letter}) {opt}")
            lines.append("")

        if q.question_type == "short_answer":
            lines.append("  Answer: ___________________________________\n")

        if include_answers:
            if q.correct_answer:
                lines.append(f"  ✓ Correct: {q.correct_answer}")
            if q.model_answer:
                lines.append(f"  ✓ Model answer: {q.model_answer}")
            if q.explanation:
                lines.append(f"  💡 {q.explanation}")
            lines.append("")

        lines.append(f"{'─' * 60}\n")

    content = "\n".join(lines)

    return PlainTextResponse(
        content=content,
        media_type="text/plain",
        headers={
            "Content-Disposition": f"attachment; filename=exam_{exam_id}.txt"
        },
    )


@router.post("/import/json", response_model=ExamResponse, status_code=status.HTTP_201_CREATED)
def import_exam_json(
    subject_id: UUID,
    data: dict,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Import an exam from JSON.

    Creates the exam and all questions. Does NOT import attempts
    (those are user-specific and should be re-taken).

    Args:
        subject_id: Subject to import into
        data: JSON with exam and questions

    Returns:
        Created exam
    """
    exam_data = data.get("exam", {})
    if not exam_data or not exam_data.get("questions"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid import data: must contain 'exam' with 'questions'",
        )

    questions_data = exam_data.get("questions", [])

    exam = Exam(
        subject_id=subject_id,
        title=exam_data.get("title", "Imported Exam"),
        description=exam_data.get("description", ""),
        question_count=len(questions_data),
        mc_count=sum(1 for q in questions_data if q.get("question_type") == "mc"),
        short_answer_count=sum(1 for q in questions_data if q.get("question_type") == "short_answer"),
        generated_from_document_ids=[],
    )
    db.add(exam)
    db.flush()

    for q_data in questions_data:
        question = ExamQuestion(
            exam_id=exam.id,
            question_order=q_data.get("question_order", 1),
            question_type=q_data.get("question_type", "mc"),
            question_text=q_data.get("question_text", ""),
            options=q_data.get("options"),
            correct_answer=q_data.get("correct_answer"),
            model_answer=q_data.get("model_answer"),
            keywords=q_data.get("keywords"),
            explanation=q_data.get("explanation", ""),
            difficulty=q_data.get("difficulty", "medium"),
            topic=q_data.get("topic", ""),
        )
        db.add(question)

    db.commit()
    db.refresh(exam)

    return exam
